### ISSUE TITLE
Panic Error (Windows Runtime)

### ISSUE THREAD

**Issue by PrototypeX37** [qbxt/no-role-kick#2]
time="2022-04-04T02:05:08+10:00" level=info msg="Connecting to DB"
time="2022-04-04T02:05:08+10:00" level=error msg="Failed to connect to database" error="Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x27d374]

**Comment by jeffreyhugh** [comment]
Did you compile this yourself or use the prebuilt binary provided in releases?

**Comment by PrototypeX37** [comment]
I tried the prebuilt. 

I compiled one myself however I managed to get it to say 
"time="2022-04-04T03:15:45+10:00" level=info msg="Bot is running, press CTRL-C to exit" userID=960204489632129134"

However the UserID listed is not the bots ID, it is the applicationID and the bot will not kick (It has admin privs) and appears offline

**Comment by PrototypeX37** [comment]
Appreciate the response :)

**Comment by jeffreyhugh** [comment]
I don't know about the user ID not being the same as the bot ID. I don't think Discord changed anything on their end, but I have not been in the Discord development ecosystem for a while so it's very possible they did. I'd say double-check the token is correct.

I also released [v1.0.1](https://github.com/qbxt/no-role-kick/releases/tag/v1.0.1) of the binary with `CGO_ENABLED=1` and verified it kicks users without issue.

**Comment by PrototypeX37** [comment]
Hiya I did double check the token and it was correct. I'll try the prebuilt again ^^

**Comment by PrototypeX37** [comment]
I was able to confirm the bot token was correct as it shows the app ID in the command like. The bot sadly still shows offline on the windows version

**Comment by jeffreyhugh** [comment]
I just made a new bot/application and the token from the [the developer dashboard](https://discord.com/developers/applications) made the bot come online and function without issue. I would advise re-generating your bot's token to ensure you have the right token.

If regenerating the token doesn't work, feel free to drop me a DM on Discord. In the meantime, I'm going to close this because the panic was addressed by a new release.
